name: Build SST Tankstellenfinder APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repository laden
      uses: actions/checkout@v3

    - name: Java installieren
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Rechte setzen
      run: chmod +x gradlew

    - name: APK bauen
      run: ./gradlew assembleDebug

    - name: APK hochladen
      uses: actions/upload-artifact@v3
      with:
        name: SST-Tankstellenfinder-APK
        path: app/build/outputs/apk/debug/app-debug.apk
